name: automatic-sd-webui
services:
  nvidia:
    build:
      context: docker
      args:
        UID: "0"
        COMMIT: "master"
    user: "0:0"
    volumes:
      - venv:/webui/venv
      - cache:/webui/cache
      - repositories:/webui/repo/repositories
      - ./sd_webui_data:/webui/repo/data
      - ./sd_webui_output:/webui/repo/outputs
    command: |
      --data-dir=/webui/repo/data
      --gradio-allowed-path=/webui/repo/data
      --listen
      --enable-insecure-extension-access
      --xformers
      --medvram
    ports:
      - "7860:7860"
    tmpfs:
      - /tmp:exec
    stdin_open: true
    tty: true
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ compute, utility ]
volumes:
  venv:
  cache:
  repositories:
